### ISSUE TITLE
Begin() Read Violation Null Pointer 

### ISSUE THREAD

**Issue by elwool** [analogdevicesinc/libsmu#200]
I'm currently trying to demo an Adalm1000 but running into issues with libsmu

Unfortunately I'm not a C++ expert. I haven't tried the python version yet - 
I was hoping to be able to drive this unit from LabView but the library isn't written in a way that I can do this directly.
So now I'm just trying to get the examples to work.

The examples all fail during begin() - read violation null ptr
![image](https://user-images.githubusercontent.com/101194262/157254399-9a30e110-aaba-47f9-87f5-18c128347a4f.png)

Is there anything obvious I should check?

**Comment by AlexandraTrifan** [comment]
Hi,

Could you provide a more detailed description on what you are trying to do?
I can see there is a Source.cpp which I believe it contains an example for libsmu. (please correct me if I am wrong). If so, could you provide the example you are running?

You did manage to build the example and it fails at runtime?
Did you manage to correctly link the example executable to libsmu?

Is the libsmu library located somewhere that is accessible from the Environment Path? It's a common process on Visual Studio builds to copy the library (libsmu.dll in this case) in the same location as your example.exe (otherwise, the executable might not find the library at runtime).  

Thank you!
-Alexandra

**Comment by elwool** [comment]
Hi Alexandra,

Source.cpp is a copy and paste  of one of the examples:
the code seems to fail on the line with the breakpoint:
![image](https://user-images.githubusercontent.com/101194262/157259448-12ac7359-2da3-4bd9-880a-b54dc24c35b5.png)

The example successfully builds, it fails at runtime.
What i did notice was that the watching the session variable shows
- m_available_devices {size=0}
- m_active_devices 1

I have placed libsmu.dll in the same directory as the example.exe

**Comment by AlexandraTrifan** [comment]
(I think libusb.dll should also be placed near libsmu.dll)
Could you provide some details on the machine you are using? OS version, 32/64bit?
We will also give it a try locally on a Windows machine to check all the build steps and figure out what might be missing.
Are you using the latest libsmu?

-Alexandra

**Comment by elwool** [comment]
Hi Alexandra,

I also put libusb.dll into the same folder

This is running Win10 21H1 64Bit
Using libsmu-1.0.4-setup-x86.exe

Thank you!
- Liam

**Comment by AlexandraTrifan** [comment]
Hi,

Can you try to build in Release mode, rather than Debug, and see if that fixes your issue?

-Alexandra

**Comment by elwool** [comment]
Hi Alexandra,

I've just tried building in release and it works. 

Oops! I possibly used release DLLs when trying to perform a debug build 🤦 

Thanks Very Much for your help, it's greatly appreciated! 
Liam
